const badgeLists = [
  {
    src: "/badgeIcons/signUp.svg",
    alt: "가입 뱃지",
    mainText: "가입 축하 기념 뱃지 획득!",
    subText: "10%를 달성하여 아래 뱃지를 획득해보세요~",
    isAcquired: true,
  },
  {
    src: "/badgeIcons/dog.svg",
    alt: "강아지 뱃지",
    mainText: "재활용률 10%를 달성하셨네요!",
    subText: "20%를 달성하여 아래 뱃지를 획득해보세요~",
    isAcquired: true,
  },
  {
    src: "/badgeIcons/appreciation.svg",
    alt: "감사 뱃지",
    mainText: "Image 1 Main Text",
    subText: "Image 1 Sub Text",
    isAcquired: true,
  },
  {
    src: "/badgeIcons/halloween.svg",
    alt: "할로윈 뱃지",
    mainText: "Image 1 Main Text",
    subText: "Image 1 Sub Text",
    isAcquired: true,
  },
  {
    src: "/badgeIcons/beach.svg",
    alt: "해변 뱃지",
    mainText: "Image 1 Main Text",
    subText: "Image 1 Sub Text",
    isAcquired: true,
  },
  {
    src: "/badgeIcons/blooming.svg",
    alt: "만개 뱃지",
    mainText: "Image 1 Main Text",
    subText: "Image 1 Sub Text",
    isAcquired: false, // 기본값은 false
  },
  {
    src: "/badgeIcons/family.svg",
    alt: "가족 뱃지",
    mainText: "Image 1 Main Text",
    subText: "Image 1 Sub Text",
    isAcquired: false,
  },
  {
    src: "/badgeIcons/shopping.svg",
    alt: "쇼핑 뱃지",
    mainText: "Image 1 Main Text",
    subText: "Image 1 Sub Text",
    isAcquired: false,
  },
  {
    src: "/badgeIcons/wedding.svg",
    alt: "결혼 뱃지",
    mainText: "Image 1 Main Text",
    subText: "Image 1 Sub Text",
    isAcquired: false,
  },
  {
    src: "/badgeIcons/cat.svg",
    alt: "고양이 뱃지",
    mainText: "Image 1 Main Text",
    subText: "Image 1 Sub Text",
    isAcquired: false,
  },
  {
    src: "/badgeIcons/waves.svg",
    alt: "레져 뱃지",
    mainText: "Image 1 Main Text",
    subText: "Image 1 Sub Text",
    isAcquired: false,
  },
  {
    src: "/badgeIcons/coffee.svg",
    alt: "커피 뱃지",
    mainText: "Image 1 Main Text",
    subText: "Image 1 Sub Text",
    isAcquired: false,
  },
  // { src: "/badgeIcon/dog.svg", alt: "강아지뱃지" },
  // { src: "/badgeIcon/shopping.svg", alt: "쇼핑뱃지" },
  // { src: "/badgeIcon/dog.svg", alt: "강아지뱃지" },
  // { src: "/badgeIcon/shopping.svg", alt: "쇼핑뱃지" },
  // { src: "/badgeIcon/dog.svg", alt: "강아지뱃지" },
  // { src: "/badgeIcon/dog.svg", alt: "강아지뱃지" },
  // 필요한 만큼 추가
];

export default badgeLists;
